
source("R/utils.R")

source("R/cache_get.R")

source("R/source_ssb.R")
source("R/source_nav.R")

source("R/install_dependencies.R")

source("R/get_kpi.R")
source("R/get_befolkning.R")
source("R/get_arbeidsstyrke.R")
source("R/get_ledighet.R")
source("R/get_rente.R")
source("R/get_valutakurs.R")
source("R/get_bnp_lopende.R")
source("R/get_bnp_fastland.R")
source("R/get_lonn.R")
source("R/get_metadata.R")
source("R/create_derived_variables.R")
source("R/get_sysselsatte.R")
source("R/get_boligpriser.R")
source("R/get_oljepris.R")
source("R/get_utenrikshandel.R")
source("R/get_oseax.R")
source("R/get_strompris.R")
source("R/get_offentlig_finans.R")
source("R/get_offentlige_utgifter.R")
source("R/get_kreditt.R")
source("R/get_boliginvesteringer.R")
source("R/get_husholdningsgjeld.R")
source("R/get_disponibel_inntekt.R")
source("R/get_offentlige_investeringer.R")
source("R/get_konsum.R")
source("R/get_sparing.R")
source("R/check_normacro.R")
source("R/search_variables.R")
source("R/describe_variable.R")
source("R/list_categories.R")
source("R/list_variables.R")
source("R/overview.R")
source("R/get_fastlandsinvesteringer.R")
source("R/validate_metadata.R")
source("R/coverage.R")
source("R/get_industriproduksjon.R")
source("R/get_byggeaktivitet.R")
source("R/get_detaljhandel.R")
source("R/get_kapasitetsutnytting.R")
source("R/get_konjunkturindikator.R")
source("R/get_ressursknapphet.R")
source("R/get_ordrebeholdning.R")
source("R/get_pengemarkedsrente.R")
source("R/get_statsrente.R")
source("R/get_tjenesteproduksjon.R")
source("R/leading_indicators.R")
source("R/conjuncture_dashboard.R")
source("R/about.R")
source("R/summary_normacro.R")
source("R/normalize_series.R")
source("R/compare_series.R")
source("R/correlation_matrix.R")
source("R/plot_correlation_matrix.R")
source("R/growth_table.R")
source("R/latest_observations.R")
source("R/missing_data.R")
source("R/compare_periods.R")

source("R/build_database.R")

source("R/get_normacro.R")
