
source("R/utils.R")

source("R/cache_get.R")

source("R/source_ssb.R")
source("R/source_nav.R")

source("R/get_kpi.R")
source("R/get_befolkning.R")
source("R/get_arbeidsstyrke.R")
source("R/get_ledighet.R")
source("R/get_rente.R")
source("R/get_valutakurs.R")
source("R/get_bnp_lopende.R")
source("R/get_bnp_fastland.R")
source("R/get_lonn.R")
source("R/get_metadata.R")
source("R/create_derived_variables.R")
source("R/get_sysselsatte.R")
source("R/get_boligpriser.R")
source("R/get_oljepris.R")
source("R/get_utenrikshandel.R")
source("R/get_oseax.R")
source("R/get_strompris.R")
source("R/get_offentlig_finans.R")
source("R/get_offentlige_utgifter.R")
source("R/get_kreditt.R")
source("R/get_boliginvesteringer.R")
source("R/get_husholdningsgjeld.R")
source("R/check_normacro.R")

source("R/build_database.R")

source("R/get_normacro.R")
