
get_metadata <- function(){
  
  tibble::tribble(
    ~Variabel, ~Beskrivelse, ~Kilde, ~Kilde_url, ~Tabell, ~Enhet, ~Frekvens, ~Startaar, ~Sluttaar, ~Funksjon, ~Kommentar,
    
    "KPI", "Konsumprisindeks", "SSB",
    "https://data.ssb.no/api/v0/no/table/pp/pp04/kpi/SBMENU12006/Kpi11",
    "14711", "2025=100", "Årlig", 1865, NA, "get_kpi",
    "Historisk KPI-serie",
    
    "Inflasjon", "Årsvekst i KPI", "Beregnet",
    NA, "KPI", "Prosent", "Årlig", 1866, NA, "get_kpi",
    "Beregnet som (KPI / lag(KPI) - 1) * 100",
    
    "Befolkning", "Befolkning 1. januar", "SSB",
    "https://data.ssb.no/api/v0/no/table/be/be05/folkemengde/SBMENU5580/FolkHistorie",
    "05803", "Personer", "Årlig", 1735, NA, "get_befolkning",
    "Historisk befolkningsserie",
    
    "Arbeidsstyrke", "Personer i arbeidsstyrken, 15-74 år", "SSB AKU",
    "https://data.ssb.no/api/v0/no/table/al/al03/aku/SBMENU9728/ArbStyrkAar",
    "03780", "Personer", "Årlig", 1972, NA, "get_arbeidsstyrke",
    "Summert menn og kvinner, multiplisert med 1000",
    
    "Sysselsatte", "Sysselsatte personer, 15-74 år", "SSB AKU",
    "https://data.ssb.no/api/v0/no/table/al/al06/aku/SBMENU9726/SysselAKUAar",
    "03781", "Personer", "Årlig", 1972, NA, "get_sysselsatte",
    "Summert menn og kvinner, multiplisert med 1000",
    
    "Arbledige_NAV", "Registrerte helt arbeidsledige", "NAV",
    "https://www.nav.no/_/attachment/download/a5aa83cd-c083-4b88-9359-1c1b3b2f936e:285ebf18c576ff0fd1537a83289401df2498cae4/Tabell%203_Helt%20ledige%20fordelt%20pa%20kjonn.Aarsgjennomsnitt.1948_2025.xls",
    "Tabell 3", "Personer", "Årlig", 1948, 2025, "get_ledighet",
    "Årsgjennomsnitt. Brudd i statistikken dokumentert av NAV",
    
    "Menn_arbledige_NAV",
    "Registrerte helt arbeidsledige menn",
    "NAV",
    "https://www.nav.no/...",
    "Tabell 3",
    "Personer",
    "Årlig",
    1948,
    2025,
    "get_ledighet",
    "Årsgjennomsnitt",
    
    "Kvinner_arbledige_NAV",
    "Registrerte helt arbeidsledige kvinner",
    "NAV",
    "https://www.nav.no/...",
    "Tabell 3",
    "Personer",
    "Årlig",
    1948,
    2025,
    "get_ledighet",
    "Årsgjennomsnitt",
    
    "Arbledighetsrate_NAV",
    "Registrerte helt arbeidsledige i prosent av arbeidsstyrken",
    "NAV",
    "https://www.nav.no/...",
    "Tabell 3",
    "Prosent",
    "Årlig",
    1948,
    2025,
    "get_ledighet",
    "Årsgjennomsnitt",
    
    "Kvinneandel_arbledige_NAV",
    "Andel kvinner blant registrerte helt arbeidsledige",
    "NAV",
    "https://www.nav.no/...",
    "Tabell 3",
    "Prosent",
    "Årlig",
    1948,
    2025,
    "get_ledighet",
    "Årsgjennomsnitt",
    
    "Styringsrente", "Norges Banks styringsrente", "Norges Bank",
    "https://data.norges-bank.no/api/data/IR/M.KPRA..?format=csv&lastNObservations=1200&locale=no&bom=include",
    "IR/M.KPRA", "Prosent", "Månedlig til årsgjennomsnitt", 1982, NA, "get_rente",
    "Årsgjennomsnitt beregnet fra månedstall",
    
    "BNP_lopende", "Bruttonasjonalprodukt, løpende priser", "SSB",
    "https://data.ssb.no/api/v0/no/table/nk/nk03/knr/SBMENU5140/NRbnp",
    "NRbnp", "Millioner kroner", "Årlig", 1970, NA, "get_bnp",
    "Nominell BNP-serie",
    
    "BNP_Fastland", "BNP Fastlands-Norge, faste priser", "SSB",
    "https://data.ssb.no/api/v0/no/table/nk/nk03/knr/SBMENU5140/NRMakroHov",
    "NRMakroHov", "Millioner kroner, faste priser", "Årlig", 1970, NA, "get_bnp_fastland",
    "Makrost = bnpb.nr23_9fn, ContentsCode = Faste",
    
    "BNP_Fastland_vekst", "Årsvekst i BNP Fastlands-Norge", "Beregnet",
    NA, "BNP_Fastland", "Prosent", "Årlig", 1971, NA, "get_bnp_fastland",
    "Beregnet som (BNP_Fastland / lag(BNP_Fastland) - 1) * 100",
    
    "Lonn", "Årslønn, påløpt", "SSB",
    "https://data.ssb.no/api/v0/no/table/al/al05/lonnansatt/SBMENU7201/NRArslonnSnitt",
    "09786", "1000 kroner", "Årlig", 1970, NA, "get_lonn",
    "Gjennomsnitt for alle lønnstakere",
    
    "Lonnvekst", "Årslønn, påløpt. Endring fra året før", "SSB",
    "https://data.ssb.no/api/v0/no/table/al/al05/lonnansatt/SBMENU7201/NRArslonnSnitt",
    "09786", "Prosent", "Årlig", 1971, NA, "get_lonn",
    "Direkte fra SSB-tabell",
    
    "Befolkningsvekst", "Årlig vekst i befolkningen", "Beregnet",
    NA, "Befolkning", "Prosent", "Årlig", 1736, NA,
    "create_derived_variables",
    "Beregnet som (Befolkning / lag(Befolkning) - 1) * 100",
    
    "Reallonnsvekst", "Lønnsvekst minus inflasjon", "Beregnet",
    NA, "Lonnvekst og Inflasjon", "Prosent", "Årlig", 1971, NA,
    "create_derived_variables",
    "Beregnet som Lonnvekst - Inflasjon",
    
    "Arbeidsstyrkeandel", "Arbeidsstyrken som andel av befolkningen", "Beregnet",
    NA, "Arbeidsstyrke og Befolkning", "Prosent", "Årlig", 1972, NA,
    "create_derived_variables",
    "Beregnet som Arbeidsstyrke / Befolkning * 100",
    
    "Arbledige_andel_arbeidsstyrke_NAV",
    "Registrerte arbeidsledige som andel av arbeidsstyrken",
    "Beregnet",
    NA,
    "Arbledige_NAV og Arbeidsstyrke",
    "Prosent",
    "Årlig",
    1972,
    NA,
    "create_derived_variables",
    "Beregnet som Arbledige_NAV / Arbeidsstyrke * 100",
    
    "Boligprisindeks",
    "Prisindeks for brukte boliger, hele landet, alle boligtyper (2015=100)",
    "SSB",
    "https://data.ssb.no/api/v0/no/table/pp/pp01/bpi/SBMENU7481/NyBoligindeks3",
    "07230",
    "Indeks (2015=100)",
    "Årlig",
    1992,
    NA,
    "get_boligpriser",
    "Hele landet, alle boligtyper",
    
    "Boligprisvekst",
    "Årlig prosentvis vekst i boligprisindeksen",
    "Beregnet",
    NA,
    "Boligprisindeks",
    "Prosent",
    "Årlig",
    1993,
    NA,
    "get_boligpriser",
    "Beregnet som (Boligprisindeks / lag(Boligprisindeks) - 1) * 100",
    
    "Oljepris_USD",
    "Brent Blend spotpris, årsgjennomsnitt",
    "FRED",
    "https://fred.stlouisfed.org/series/DCOILBRENTEU",
    "DCOILBRENTEU",
    "USD per fat",
    "Årlig",
    1987,
    NA,
    "get_oljepris",
    "Årsgjennomsnitt av daglige Brent-observasjoner",
    
    "Oljeprisvekst",
    "Årlig prosentvis vekst i Brent oljepris",
    "Beregnet",
    NA,
    "Oljepris_USD",
    "Prosent",
    "Årlig",
    1988,
    NA,
    "get_oljepris",
    "Beregnet som (Oljepris_USD / lag(Oljepris_USD) - 1) * 100",
    
    "Valutakurs_I44",
    "Importveid kronekursindeks I-44",
    "Norges Bank",
    "https://data.norges-bank.no/api/data/EXR/A.I44.NOK.SP?format=csv&lastNObservations=100&locale=no",
    "EXR/A.I44.NOK.SP",
    "Indeks",
    "Årlig",
    1990,
    NA,
    "get_valutakurs",
    "Høyere verdi betyr svakere krone",
    
    "Valutakurs_I44_vekst",
    "Årlig prosentvis vekst i importveid kronekursindeks I-44",
    "Beregnet",
    NA,
    "Valutakurs_I44",
    "Prosent",
    "Årlig",
    1991,
    NA,
    "get_valutakurs",
    "Beregnet som (Valutakurs_I44 / lag(Valutakurs_I44) - 1) * 100. Positiv verdi betyr svakere krone",
    
    "Eksport",
    "Eksport i alt, faste 2023-priser",
    "SSB",
    "https://data.ssb.no/api/v0/no/table/nk/nk03/knr/SBMENU5140/NRMakroHov",
    "09189",
    "Millioner kroner, faste 2023-priser",
    "Årlig",
    1970,
    NA,
    "get_utenrikshandel",
    "Makrost = eks.nrtot, ContentsCode = Faste",
    
    "Import",
    "Import i alt, faste 2023-priser",
    "SSB",
    "https://data.ssb.no/api/v0/no/table/nk/nk03/knr/SBMENU5140/NRMakroHov",
    "09189",
    "Millioner kroner, faste 2023-priser",
    "Årlig",
    1970,
    NA,
    "get_utenrikshandel",
    "Makrost = imp.nrtot, ContentsCode = Faste",
    
    "Eksportvekst",
    "Årlig prosentvis vekst i eksport",
    "Beregnet",
    NA,
    "Eksport",
    "Prosent",
    "Årlig",
    1971,
    NA,
    "get_utenrikshandel",
    "Beregnet som (Eksport / lag(Eksport) - 1) * 100",
    
    "Importvekst",
    "Årlig prosentvis vekst i import",
    "Beregnet",
    NA,
    "Import",
    "Prosent",
    "Årlig",
    1971,
    NA,
    "get_utenrikshandel",
    "Beregnet som (Import / lag(Import) - 1) * 100",
    
    "OSEAX",
    "Oslo Stock Exchange All-Share Index (årsgjennomsnitt)",
    "Yahoo Finance",
    "https://finance.yahoo.com/quote/%5EOSEAX/",
    "^OSEAX",
    "Indeks",
    "Årlig",
    2013,
    NA,
    "get_oseax",
    "Årsgjennomsnitt av daglige observasjoner",
    
    "OSEAX_vekst",
    "Årlig prosentvis vekst i OSEAX",
    "Beregnet",
    NA,
    "OSEAX",
    "Prosent",
    "Årlig",
    2014,
    NA,
    "get_oseax",
    "Beregnet som (OSEAX / lag(OSEAX) - 1) * 100",
    
    "Strompris",
    "Kraft og nett i alt inklusive avgifter for husholdninger",
    "SSB",
    "https://data.ssb.no/api/v0/no/table/ei/ei01/elkraftpris/SBMENU4023/KraftPrisNettLeiAar",
    "09007",
    "Øre per kWh",
    "Årlig",
    2012,
    NA,
    "get_strompris",
    "Kraft og nett i alt inkl. avgifter",
    
    "Stromprisvekst",
    "Årlig prosentvis vekst i strømpris",
    "Beregnet",
    NA,
    "Strompris",
    "Prosent",
    "Årlig",
    2013,
    NA,
    "get_strompris",
    "Beregnet som (Strompris / lag(Strompris) - 1) * 100",
    
    "Offentlig_gjeld",
    "Offentlig forvaltnings gjeld i alt",
    "SSB",
    "https://data.ssb.no/api/v0/no/table/os/os04/offogjeld/SBMENU5263/FinansUnder",
    "07511",
    "Millioner kroner",
    "Årlig",
    1995,
    NA,
    "get_offentlig_finans",
    "Sektor = Offentlig forvaltning, FinansObjekt = GJELD I ALT",
    
    "Offentlig_nettofordringer",
    "Offentlig forvaltnings nettofordringer",
    "SSB",
    "https://data.ssb.no/api/v0/no/table/os/os04/offogjeld/SBMENU5263/FinansUnder",
    "07511",
    "Millioner kroner",
    "Årlig",
    1995,
    NA,
    "get_offentlig_finans",
    "Sektor = Offentlig forvaltning, FinansObjekt = Nettofordringer",
    
    "Offentlig_gjeld_andel_BNP",
    "Offentlig gjeld som andel av BNP",
    "Beregnet",
    NA,
    "Offentlig_gjeld og BNP_lopende",
    "Prosent",
    "Årlig",
    1995,
    NA,
    "create_derived_variables",
    "Beregnet som Offentlig_gjeld / BNP_lopende * 100",
    
    "Offentlig_nettofordringer_andel_BNP",
    "Offentlige nettofordringer som andel av BNP",
    "Beregnet",
    NA,
    "Offentlig_nettofordringer og BNP_lopende",
    "Prosent",
    "Årlig",
    1995,
    NA,
    "create_derived_variables",
    "Beregnet som Offentlig_nettofordringer / BNP_lopende * 100",
    
    "Offentlige_utgifter", "Offentlig forvaltnings totale utgifter", "SSB",
    "https://data.ssb.no/api/v0/no/table/os/os02/offinnut/SBMENU4642/OffInnUt21",
    "14668", "Millioner kroner", "Årlig", 1995, NA, "get_offentlige_utgifter",
    "Art = Totale utgifter (B+D), Sektor = Offentlig forvaltning",
    
    "Statlige_utgifter", "Statsforvaltningens totale utgifter", "SSB",
    "https://data.ssb.no/api/v0/no/table/os/os02/offinnut/SBMENU4642/OffInnUt21",
    "14668", "Millioner kroner", "Årlig", 1995, NA, "get_offentlige_utgifter",
    "Art = Totale utgifter (B+D), Sektor = Statsforvaltningen",
    
    "Kommunale_utgifter", "Kommuneforvaltningens totale utgifter", "SSB",
    "https://data.ssb.no/api/v0/no/table/os/os02/offinnut/SBMENU4642/OffInnUt21",
    "14668", "Millioner kroner", "Årlig", 1995, NA, "get_offentlige_utgifter",
    "Art = Totale utgifter (B+D), Sektor = Kommuneforvaltningen",
    
    "Kommunal_utgiftsandel", "Kommunale utgifter som andel av offentlige utgifter", "Beregnet",
    NA, "Kommunale_utgifter og Offentlige_utgifter", "Prosent", "Årlig", 1995, NA,
    "create_derived_variables", "Beregnet som Kommunale_utgifter / Offentlige_utgifter * 100",
    
    "Statlig_utgiftsandel", "Statlige utgifter som andel av offentlige utgifter", "Beregnet",
    NA, "Statlige_utgifter og Offentlige_utgifter", "Prosent", "Årlig", 1995, NA,
    "create_derived_variables", "Beregnet som Statlige_utgifter / Offentlige_utgifter * 100",
    
    "Kreditt_K2",
    "Innenlandsk lånegjeld til publikum, årsgjennomsnitt",
    "SSB",
    "https://data.ssb.no/api/v0/no/table/bf/bf02/kredind/InnLandGjeldNY",
    "06718",
    "Millioner kroner",
    "Årlig",
    1987,
    NA,
    "get_kreditt",
    "Valuta = I alt, låntakersektor = Publikum, kredittkilde = alle långivere. Årsgjennomsnitt av månedstall",
    
    "Kredittvekst_K2",
    "Årlig prosentvis vekst i innenlandsk lånegjeld til publikum",
    "Beregnet",
    NA,
    "Kreditt_K2",
    "Prosent",
    "Årlig",
    1988,
    NA,
    "get_kreditt",
    "Beregnet som (Kreditt_K2 / lag(Kreditt_K2) - 1) * 100",
    
    "Boliginvesteringer",
    "Boliginvesteringer i husholdninger, faste 2023-priser",
    "SSB",
    "https://data.ssb.no/api/v0/no/table/nk/nk03/knr/SBMENU5140/NRMakroHov",
    "09189",
    "Millioner kroner (2023-priser)",
    "Årlig",
    1970,
    NA,
    "get_boliginvesteringer",
    "Boliger (husholdninger), bruttoinvestering i fast realkapital",
    
    "Boliginvesteringer_vekst",
    "Årlig vekst i boliginvesteringer",
    "Beregnet",
    NA,
    "Boliginvesteringer",
    "Prosent",
    "Årlig",
    1971,
    NA,
    "get_boliginvesteringer",
    "Beregnet som (Boliginvesteringer / lag(Boliginvesteringer) - 1) * 100",
    
    "Boliginvesteringer_andel_BNP",
    "Boliginvesteringer som andel av BNP Fastlands-Norge",
    "Beregnet",
    NA,
    "Boliginvesteringer og BNP_Fastland",
    "Prosent",
    "Årlig",
    1970,
    NA,
    "create_derived_variables",
    "Beregnet som Boliginvesteringer / BNP_Fastland * 100",
    
    "Husholdningsgjeldsrate", "Husholdningenes gjeldsrate", "SSB",
    "https://data.ssb.no/api/v0/no/table/nk/nk01/finsek/div_finsek_mappe/FinansSektReg9",
    "09477", "Prosent", "Årlig", 1996, NA, "get_husholdningsgjeld",
    "Ujustert. Årsgjennomsnitt av kvartalstall",
    
    "Husholdningsfordringsrate", "Husholdningenes fordringsrate", "SSB",
    "https://data.ssb.no/api/v0/no/table/nk/nk01/finsek/div_finsek_mappe/FinansSektReg9",
    "09477", "Prosent", "Årlig", 1996, NA, "get_husholdningsgjeld",
    "Ujustert. Årsgjennomsnitt av kvartalstall",
    
    "Husholdningsnettofordringsrate", "Husholdningenes nettofordringsrate", "SSB",
    "https://data.ssb.no/api/v0/no/table/nk/nk01/finsek/div_finsek_mappe/FinansSektReg9",
    "09477", "Prosent", "Årlig", 1996, NA, "get_husholdningsgjeld",
    "Ujustert. Årsgjennomsnitt av kvartalstall",
    
    "Husholdningsgjeldsvekst", "Husholdningenes gjeldsvekst", "SSB",
    "https://data.ssb.no/api/v0/no/table/nk/nk01/finsek/div_finsek_mappe/FinansSektReg9",
    "09477", "Prosent", "Årlig", 1996, NA, "get_husholdningsgjeld",
    "Ujustert. Årsgjennomsnitt av kvartalstall",
    
    "BNP_Fastland_per_innbygger",
    "BNP Fastlands-Norge per innbygger",
    "Beregnet",
    NA,
    "BNP_Fastland og Befolkning",
    "1000 kroner per innbygger",
    "Årlig",
    1970,
    NA,
    "create_derived_variables",
    "Beregnet som BNP_Fastland / Befolkning",
    
    "BNP_Fastland_per_innbygger_vekst",
    "Årlig vekst i BNP Fastlands-Norge per innbygger",
    "Beregnet",
    NA,
    "BNP_Fastland_per_innbygger",
    "Prosent",
    "Årlig",
    1971,
    NA,
    "create_derived_variables",
    "Beregnet som (BNP_Fastland_per_innbygger / lag(BNP_Fastland_per_innbygger) - 1) * 100",
    
    "BNP_lopende_per_innbygger",
    "BNP i løpende priser per innbygger",
    "Beregnet",
    NA,
    "BNP_lopende og Befolkning",
    "1000 kroner per innbygger",
    "Årlig",
    1970,
    NA,
    "create_derived_variables",
    "Beregnet som BNP_lopende / Befolkning",
    
    "Arbeidsproduktivitet",
    "BNP Fastlands-Norge per sysselsatt",
    "Beregnet",
    NA,
    "BNP_Fastland og Sysselsatte",
    "Millioner kroner per sysselsatt",
    "Årlig",
    1972,
    NA,
    "create_derived_variables",
    "Beregnet som BNP_Fastland / Sysselsatte",
    
    "Produktivitetsvekst",
    "Årlig vekst i arbeidsproduktivitet",
    "Beregnet",
    NA,
    "Arbeidsproduktivitet",
    "Prosent",
    "Årlig",
    1973,
    NA,
    "create_derived_variables",
    "Beregnet som (Arbeidsproduktivitet / lag(Arbeidsproduktivitet) - 1) * 100",
    
    "Offentlige_investeringer",
    "Bruttoinvesteringer i offentlig forvaltning",
    "SSB",
    "https://data.ssb.no/api/v0/no/table/nk/nk03/knr/SBMENU5140/NRMakroHov",
    "Makrost=bif.nr83_6",
    "Millioner kroner (faste 2023-priser)",
    "Årlig",
    1970,
    2025,
    "get_offentlige_investeringer",
    "Bruttoinvesteringer i offentlig forvaltning i faste 2023-priser",
    
    "Offentlige_investeringer_vekst",
    "Årlig vekst i offentlige investeringer",
    "Beregnet",
    NA,
    "Offentlige_investeringer",
    "Prosent",
    "Årlig",
    1971,
    NA,
    "get_offentlige_investeringer",
    "Beregnet som (Offentlige_investeringer / lag(Offentlige_investeringer) - 1) * 100",
    
    "Offentlige_investeringer_andel_BNP",
    "Offentlige investeringer som andel av BNP Fastlands-Norge",
    "Beregnet",
    NA,
    "Offentlige_investeringer og BNP_Fastland",
    "Prosent",
    "Årlig",
    1970,
    NA,
    "create_derived_variables",
    "Beregnet som Offentlige_investeringer / BNP_Fastland * 100"
  )
}